//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_DAEntities : DbContext
    {
        public QL_DAEntities()
            : base("name=QL_DAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DuAn> DuAn { get; set; }
        public virtual DbSet<LichSuNhiemVu> LichSuNhiemVu { get; set; }
        public virtual DbSet<NganSach> NganSach { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<NhiemVu> NhiemVu { get; set; }
        public virtual DbSet<PhanHoi> PhanHoi { get; set; }
        public virtual DbSet<PhanTichRuiRo> PhanTichRuiRo { get; set; }
        public virtual DbSet<QuyenTruyCap> QuyenTruyCap { get; set; }
        public virtual DbSet<Sprint> Sprint { get; set; }
        public virtual DbSet<TaiLieu> TaiLieu { get; set; }
        public virtual DbSet<ThanhVienDuAn> ThanhVienDuAn { get; set; }
        public virtual DbSet<ThongBao> ThongBao { get; set; }
    }
}
