//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNhiemVu
    {
        public int LichSuID { get; set; }
        public int NhiemVuID { get; set; }
        public int NguoiThayDoiID { get; set; }
        public string MoTaThayDoi { get; set; }
        public System.DateTime NgayThayDoi { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhiemVu NhiemVu { get; set; }
    }
}
