//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;



    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.LichSuNhiemVu = new HashSet<LichSuNhiemVu>();
            this.NhiemVu = new HashSet<NhiemVu>();
            this.PhanHoi = new HashSet<PhanHoi>();
            this.QuyenTruyCap = new HashSet<QuyenTruyCap>();
            this.TaiLieu = new HashSet<TaiLieu>();
            this.ThanhVienDuAn = new HashSet<ThanhVienDuAn>();
            this.ThongBao = new HashSet<ThongBao>();
        }
        [DisplayName("ID")]
        public int NguoiDungID { get; set; }

        [DisplayName("Account")]
        [Required(ErrorMessage = "Not Empty")]
        public string TenDangNhap { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Not Empty")]
        public string MatKhau { get; set; }

        [NotMapped]
        [DisplayName("Confirm Password")]
        [Compare("MatKhau", ErrorMessage = "Mật khẩu không khớp.")]
        public string NhapLaiMatKhau { get; set; }

        [DisplayName("Full name")]
        [Required(ErrorMessage = "Not Empty")]
        public string HoTen { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Not Empty")]
        public string Email { get; set; }

        [DisplayName("Role")]
        [Required(ErrorMessage = "Not Empty")]
        public string VaiTro { get; set; }

        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> LanDangNhapCuoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuNhiemVu> LichSuNhiemVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhiemVu> NhiemVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyenTruyCap> QuyenTruyCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiLieu> TaiLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhVienDuAn> ThanhVienDuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBao { get; set; }
    }
}
