//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhiemVu()
        {
            this.LichSuNhiemVu = new HashSet<LichSuNhiemVu>();
        }
    
        public int NhiemVuID { get; set; }
        public int DuAnID { get; set; }
        public int NguoiDuocGiaoID { get; set; }
        public string TenNhiemVu { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> HanHoanThanh { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuNhiemVu> LichSuNhiemVu { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
