//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ThongBaoID { get; set; }
        public int NguoiDungID { get; set; }
        public string NoiDung { get; set; }
        public bool DaXem { get; set; }
        public System.DateTime NgayGui { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
